# Generated by Django 3.2.9 on 2022-12-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startups',
            name='date_approval',
            field=models.DateTimeField(null=True),
        ),
    ]
