# Generated by Django 3.2.9 on 2022-12-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
