# Generated by Django 3.2.9 on 2022-12-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
