# Generated by Django 3.2.9 on 2022-12-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
