# Generated by Django 3.0.6 on 2023-01-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0012_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='startups',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
